name: Reusable Docker Build and Push

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      dockerfile-path:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      ecr-repository:
        required: true
        type: string
    secrets:
      aws-role-arn:
        required: true
    outputs:
      image-tag:
        description: "Full image tag"
        value: ${{ jobs.build-push.outputs.image-tag }}

jobs:
  build-push:
    name: Build and Push ${{ inputs.service-name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    outputs:
      image-tag: ${{ steps.build-image.outputs.image-tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-role-arn }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr-repository }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            -f ${{ inputs.dockerfile-path }} \
            .
          echo "image-tag=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Image scan
        continue-on-error: true
        run: |
          aws ecr start-image-scan \
            --repository-name ${{ inputs.ecr-repository }} \
            --image-id imageTag=${{ github.sha }} \
            --region ${{ inputs.aws-region }}

